Repository Cow-Coder/cow-Low-code, pull requests merged in 2022-08, with the labels that each got.

#17 Feat/preview
  src/components/base-ui/kzy-draggable/index.vue
  src/components/page-draggable/index.vue
  src/views/home/components/edit-panel.vue
  src/views/home/components/float-tips.vue
Labels: bug

#16 新物料：textbox的基本功能
  src/library/generic/input/button/index.vue
  src/library/generic/input/textbox/index.vue
  src/library/generic/show/image/index.vue
  src/stores/code.ts
  src/types/library-component.ts
  src/types/panel.ts
  src/views/home/components/home-right/components/attribute-panel/components/form-render/components/form-item-list/components/IndefiniteNumberInputBox/index.module.scss
  src/views/home/components/home-right/components/attribute-panel/components/form-render/components/form-item-list/components/IndefiniteNumberInputBox/index.tsx
  src/views/home/components/home-right/components/attribute-panel/components/form-render/components/form-item-list/components/SwitchWithSlots.tsx
  src/views/home/components/home-right/components/attribute-panel/components/form-render/components/form-item-list/index.tsx
  src/views/home/components/home-right/components/attribute-panel/components/form-render/index.tsx
  src/views/home/components/home-right/components/attribute-panel/index.vue
  types/components.d.ts
Labels: enhancement

#21 fix(attributePanel): 修复物料按钮挤压
  src/components/base-ui/kzy-draggable/index.vue
  src/components/page-draggable/index.vue
  src/views/home/components/home-left/components/library-category-tab-panes/components/library-category-tab-pane-base.vue
Labels: bug

#19 Feat/event
  src/hooks/use-multi-click.ts
  src/library/generic/input/button/index.vue
  src/types/library-component-event.ts
  src/utils/library.ts
  src/views/home/components/action-config-dialog/action-config-dialog.vue
  src/views/home/components/action-config-dialog/action-handlers/other/copy/index.tsx
  src/views/home/components/action-config-dialog/action-handlers/other/index.tsx
  src/views/home/components/action-config-dialog/action-handlers/other/javascript/index.tsx
  src/views/home/components/action-config-dialog/action-handlers/page/index.tsx
  src/views/home/components/action-config-dialog/action-handlers/page/open-page/index.tsx
  src/views/home/components/action-config-dialog/action-handlers/service/download/index.tsx
  src/views/home/components/action-config-dialog/action-handlers/service/index.tsx
  src/views/home/components/action-config-dialog/action-handlers/service/request/index.tsx
  src/views/home/components/action-config-dialog/action.ts
  src/views/home/components/action-config-dialog/index.tsx
  src/views/home/components/edit-panel.vue
  src/views/home/components/float-tips.vue
  src/views/home/components/home-right/components/attribute-panel/components/event-tab-pane.vue
  src/views/home/components/home-right/components/attribute-panel/index.vue
  src/views/home/index.vue
  types/components.d.ts
  types/vue.d.ts
Labels: enhancement

#27 fix(attributePanel): 无法拖动
  src/components/base-ui/kzy-draggable/index.vue
  src/components/page-draggable/index.vue
  src/views/home/components/home-left/components/library-category-tab-panes/components/library-category-tab-pane-base.vue
Labels: bug

#30 Docs/update
  README.md
Labels: documentation

#31 docs: add LICENSE
  LICENSE
Labels: documentation

#32 docs: 刷新徽标缓存
  README.md
Labels: documentation

#34 Docs/logo
  README.md
  src/assets/images/logo.svg
Labels: documentation

#45 事件面板action拖拽动画&编辑器拖拽物料组件动画
  src/components/base-ui/kzy-draggable/types.ts
  src/directive/element-dialog-resize/index.ts
  src/directive/element-dialog-resize/use-draggable.ts
  src/directive/element-dialog-resize/use-parse-translate.ts
  src/directive/element-dialog-resize/use-resizer.ts
  src/directive/index.ts
  src/main.ts
  src/utils/type.ts
  src/views/home/components/edit-panel.vue
  src/views/home/components/home-right/components/attribute-panel/components/event-tab-pane.vue
Labels: enhancement

#44 feat: dialog缩放大小directive
  src/directive/element-dialog-resize/index.ts
  src/directive/element-dialog-resize/use-draggable.ts
  src/directive/element-dialog-resize/use-parse-translate.ts
  src/directive/element-dialog-resize/use-resizer.ts
  src/directive/index.ts
  src/main.ts
  src/utils/type.ts
Labels: enhancement

#42 添加logo，修正preview预览命令
  package.json
  src/views/home/components/home-header.vue
Labels: enhancement

#46 :bug: code-tab-pane自动格式化
  package-lock.json
  package.json
  src/components/monaco-editor/index.vue
  src/constant/index.ts
  src/directive/element-dialog-resize/index.ts
  src/directive/element-dialog-resize/use-draggable.ts
  src/directive/element-dialog-resize/use-resizer.ts
  src/types/library-component-event.ts
  src/types/library-component.ts
  src/utils/library.ts
  src/views/home/components/home-left/components/code-tab-pane.vue
  src/views/home/components/home-left/index.vue
  src/views/home/components/home-right/components/attribute-panel/components/event-tab-pane/index.vue
  src/views/home/components/home-right/components/attribute-panel/components/event-tab-pane/use-event-action.tsx
  src/views/home/components/home-right/components/attribute-panel/components/event-tab-pane/use-event-tab-pane.tsx
  src/views/home/components/home-right/components/attribute-panel/components/event-tab-pane/use-event-trigger.ts
  src/views/home/components/home-right/components/attribute-panel/config.ts
Labels: bug

#48 fix(edit-panel): 预览按键修改为space
  src/views/home/components/edit-panel.vue
  src/views/home/components/float-tips.vue
Labels: bug

#50 Fix/monaco
  src/components/monaco-editor/index.vue
  src/views/home/components/home-left/components/code-tab-pane.vue
  src/views/home/components/home-right/components/attribute-panel/components/event-tab-pane/index.vue
  src/views/home/components/home-right/components/attribute-panel/components/event-tab-pane/use-event-trigger.ts
Labels: bug, enhancement

#52 Feat/custom event trigger
  src/components/monaco-editor/index.vue
  src/types/library-component-event.ts
  src/views/home/components/action-config-dialog/action-config-dialog.vue
  src/views/home/components/action-config-dialog/action-handlers/component/index.ts
  src/views/home/components/action-config-dialog/action-handlers/other/copy/index.tsx
  src/views/home/components/action-config-dialog/action-handlers/other/index.tsx
  src/views/home/components/action-config-dialog/action-handlers/other/javascript/index.tsx
  src/views/home/components/action-config-dialog/action-handlers/page/index.tsx
  src/views/home/components/action-config-dialog/action-handlers/service/download/index.tsx
  src/views/home/components/action-config-dialog/action-handlers/service/index.tsx
  src/views/home/components/action-config-dialog/action-handlers/service/request/index.tsx
  src/views/home/components/action-config-dialog/action.ts
  src/views/home/components/action-config-dialog/index.tsx
  src/views/home/components/action-config-dialog/types.ts
  src/views/home/components/action-config-dialog/util.ts
  src/views/home/components/home-right/components/attribute-panel/components/event-tab-pane/index.vue
  src/views/home/components/home-right/components/attribute-panel/components/event-tab-pane/use-event-tab-pane.tsx
  src/views/home/components/home-right/components/attribute-panel/components/event-tab-pane/use-event-trigger.ts
  src/views/home/components/home-right/components/attribute-panel/components/event-tab-pane/util.ts
  types/components.d.ts
Labels: enhancement

#55 :construction: Feat/custom event trigger
  src/components/monaco-editor/index.vue
  src/types/library-component-event.ts
  src/views/home/components/action-config-dialog/action-config-dialog.vue
  src/views/home/components/action-config-dialog/action-handlers/component/index.ts
  src/views/home/components/action-config-dialog/action-handlers/other/copy/index.tsx
  src/views/home/components/action-config-dialog/action-handlers/other/index.tsx
  src/views/home/components/action-config-dialog/action-handlers/other/javascript/index.tsx
  src/views/home/components/action-config-dialog/action-handlers/page/index.tsx
  src/views/home/components/action-config-dialog/action-handlers/service/download/index.tsx
  src/views/home/components/action-config-dialog/action-handlers/service/index.tsx
  src/views/home/components/action-config-dialog/action-handlers/service/request/index.tsx
  src/views/home/components/action-config-dialog/action.ts
  src/views/home/components/action-config-dialog/index.tsx
  src/views/home/components/action-config-dialog/types.ts
  src/views/home/components/action-config-dialog/util.ts
  src/views/home/components/home-left/components/code-tab-pane.vue
  src/views/home/components/home-right/components/attribute-panel/components/event-tab-pane/index.vue
  src/views/home/components/home-right/components/attribute-panel/components/event-tab-pane/use-event-tab-pane.tsx
  src/views/home/components/home-right/components/attribute-panel/components/event-tab-pane/use-event-trigger.ts
  src/views/home/components/home-right/components/attribute-panel/components/event-tab-pane/util.ts
  types/components.d.ts
Labels: duplicate

#56 :zap: perf: 更改页面布局方式为fixed，提高缩放面板时的性能
  .gitignore
  config/plugins/visualizer.ts
  config/vite.config.base.ts
  src/App.vue
  src/assets/style/global.scss
  src/components/base-ui/kzy-draggable/index.vue
  src/components/monaco-editor/index.vue
  src/components/monaco-editor/use-features.ts
  src/components/monaco-editor/use-languages.ts
  src/components/monaco-editor/use-monaco.ts
  src/router/index.ts
  src/views/home/components/action-config-dialog/action-config-dialog.vue
  src/views/home/components/action-config-dialog/index.tsx
  src/views/home/components/home-left/index.vue
  src/views/home/components/home-right/components/attribute-panel/components/event-tab-pane/index.vue
  src/views/home/components/home-right/components/attribute-panel/index.vue
  src/views/home/components/home-right/index.vue
  src/views/home/index.scss
  src/views/home/index.vue
  types/color-picker.d.ts
  types/global.d.ts
Labels: enhancement

#58 Feat/monaco zh
  .husky/pre-commit
  .npmrc
  config/plugins/api-import.ts
  config/plugins/arco-style-import.ts
  config/plugins/components-import.ts
  config/plugins/element-style-and-icon.ts
  config/plugins/manual-chunks.ts
  config/plugins/monaco.ts
  config/vite.config.base.ts
  package-lock.json
  package.json
  types/auto-imports.d.ts
Labels: enhancement

#71 fix: 无法拖拽进画布
  src/views/home/components/edit-panel.vue
Labels: bug

#78 Revert "feat(library): 添加步进器表单渲染，增加圆形进度条物料" 构建失败
  src/library/generic/show/circle/index.vue
  src/types/panel.ts
  src/views/home/components/home-right/components/attribute-panel/components/form-render/components/form-item-list/components/Stepper/index.module.scss
  src/views/home/components/home-right/components/attribute-panel/components/form-render/components/form-item-list/components/Stepper/index.tsx
  src/views/home/components/home-right/components/attribute-panel/components/form-render/components/form-item-list/index.tsx
  types/components.d.ts
Labels: bug

#81 ci: 构建docs
  .github/workflows/deploy-docs.yml
  .github/workflows/deploy-preview.yml
  package.json
Labels: documentation

#82 feat(editor): [libraryPanel] 左下角添加查看文档和关于项目
  README.md
  docs/.vitepress/config.ts
  docs/.vitepress/theme/components/customer-evaluate.vue
  docs/.vitepress/theme/components/home-preview.vue
  docs/.vitepress/theme/components/zoom-img.vue
  docs/.vitepress/theme/index.ts
  docs/development/dictionary.md
  docs/package.json
  docs/public/img.png
  docs/public/img_1.png
  docs/public/img_2.png
  docs/public/img_3.png
  docs/public/img_4.png
  docs/public/img_5.png
  docs/vite.config.ts
  packages/editor/src/views/home/components/home-left/index.vue
  packages/editor/src/views/home/index.vue
  pnpm-lock.yaml
Labels: bug, enhancement

#83 fix(docs): 回退vitepress版本
  docs/.vitepress/config.ts
  docs/.vitepress/theme/index.ts
  docs/guide/summary.md
  docs/package.json
  pnpm-lock.yaml
Labels: bug

#85 完成文档
  README.md
  docs/.vitepress/config.ts
  docs/development/add-event-action.md
  docs/development/add-library-component.md
  docs/development/build.md
  docs/development/coding-style.md
  docs/development/dictionary-style.md
  docs/development/dictionary.md
  docs/development/git-style.md
  docs/development/icon.md
  docs/development/lint.md
  docs/development/prepare.md
  docs/development/question.md
  docs/development/start.md
  docs/development/style-design.md
  docs/development/typescript.md
  docs/development/unit-test.md
  docs/development/update-by-git.md
  docs/guide/component.md
  docs/guide/event-and-action.md
  docs/guide/question.md
  docs/guide/style.md
  docs/guide/summary.md
  packages/editor/config/utils/index.ts
  packages/editor/config/vite.config.base.ts
  packages/editor/config/vite.config.dev.ts
  packages/editor/config/vite.config.prod.ts
  packages/editor/src/views/home/components/home-left/index.vue
Labels: documentation

#87 优化文档
  .gitignore
  .vscode/settings.json
  docs/.vitepress/config.ts
  docs/.vitepress/theme/components/zoom-img.vue
  docs/development/copywriting-style.md
  docs/development/dictionary-style.md
  docs/development/dictionary.md
  docs/development/docs.md
  docs/package.json
  docs/public/monorepo.svg
  package.json
  pnpm-lock.yaml
Labels: documentation

#89 feat(library): 添加circle物料，添加步进器表单类型
  packages/editor/src/views/home/components/home-right/components/attribute-panel/components/form-render/components/form-item-list/components/Stepper/index.module.scss
  packages/editor/src/views/home/components/home-right/components/attribute-panel/components/form-render/components/form-item-list/components/Stepper/index.tsx
  packages/editor/src/views/home/components/home-right/components/attribute-panel/components/form-render/components/form-item-list/index.tsx
  packages/editor/types/components.d.ts
  packages/library/src/components/generic/show/circle/index.vue
  packages/types/src/panel.ts
Labels: bug

#91 fix(editor): 修复v-element-dialog-resize指令只能首次生效
  commitlint.config.js
  packages/editor/src/components/monaco-editor/index.vue
  packages/editor/src/directive/element-dialog-resize/index.tsx
  packages/editor/src/directive/element-dialog-resize/use-css-variable.ts
  packages/editor/src/directive/element-dialog-resize/use-fullscreen.tsx
  packages/editor/src/directive/element-dialog-resize/use-resizer.ts
  packages/editor/src/stores/code.ts
  packages/editor/src/utils/type.ts
  packages/editor/src/views/home/components/edit-panel/index.vue
  packages/editor/src/views/home/components/home-header/use-preset-event.ts
  packages/editor/src/views/home/components/home-right/components/attribute-panel/components/event-tab-pane/components/action-config-dialog/action-config-dialog.vue
  packages/editor/src/views/home/components/home-right/components/attribute-panel/components/event-tab-pane/use-event-trigger.ts
  packages/editor/src/views/home/components/home-right/components/attribute-panel/components/form-render/index.tsx
  packages/editor/src/views/home/components/home-right/components/attribute-panel/components/generic-tab-pane.vue
  packages/editor/src/views/home/components/home-right/components/attribute-panel/config.ts
  packages/event-action/index.ts
  packages/event-action/src/actions/other/copy/index.tsx
  packages/event-action/src/actions/other/javascript/index.tsx
  packages/event-action/src/hooks/use-merge-props-and-config.ts
  packages/event-action/src/utils/util.ts
  packages/library/src/components/generic/show/swipe/index.vue
  packages/preview/src/stores/code.ts
  packages/preview/src/views/home/index.vue
  packages/types/src/action.ts
  packages/types/src/library-component.ts
  packages/utils/src/library.ts
Labels: bug, enhancement

#92 feat(editor): 撤销重做
  docs/.vitepress/config.ts
  docs/_data/team.js
  docs/development/style-design.md
  docs/document/divide.md
  docs/document/start.md
  docs/guide/custom-action.md
  docs/guide/custom-trigger.md
  docs/guide/preset.md
  docs/guide/preview.md
  docs/guide/style.md
  docs/tsconfig.json
  docs/vite.config.ts
  packages/editor/index.html
  packages/editor/package.json
  packages/editor/src/views/home/components/home-header/index.vue
  packages/editor/src/views/home/components/home-header/use-preset.ts
  packages/editor/src/views/home/components/home-header/use-stateshot.ts
  pnpm-lock.yaml
Labels: enhancement

#95 ci: 更新pnpm-lock
  .vscode/settings.json
  packages/preview/types/auto-imports.d.ts
  pnpm-lock.yaml
Labels: bug

#96 fix: 拖拽预览
  packages/editor/src/components/base-ui/kzy-draggable/index.vue
  packages/editor/src/components/page-draggable/index.vue
  packages/editor/src/views/home/components/edit-panel/index.vue
  packages/editor/src/views/home/components/edit-panel/use-content-menu.tsx
  packages/editor/src/views/home/components/edit-panel/use-drag-preview.tsx
  packages/editor/src/views/home/components/edit-panel/use-parse-library.tsx
  packages/editor/src/views/home/components/edit-panel/use-prevent-touch.tsx
  packages/editor/src/views/home/components/home-header/index.vue
  packages/editor/src/views/home/components/home-left/components/library-category-tab-panes/components/library-category-tab-pane-base.vue
  packages/editor/src/views/home/index.vue
  packages/library/src/components/generic/form/button/index.vue
  packages/library/src/components/generic/show/circle/index.vue
  packages/library/src/components/generic/show/image/index.vue
  packages/library/src/components/generic/show/notice-bar/index.vue
  packages/library/src/components/generic/show/swipe/index.vue
Labels: bug

#98 Feat/apprence
  packages/editor/src/views/home/components/home-right/components/attribute-panel/components/appearance-tab-pane.vue
  packages/editor/src/views/home/components/home-right/components/attribute-panel/components/form-render/components/form-item-list/components/CssPropertyInput/components/css-panel/index.vue
  packages/editor/src/views/home/components/home-right/components/attribute-panel/components/form-render/components/form-item-list/components/CssPropertyInput/index.tsx
  packages/editor/src/views/home/components/home-right/components/attribute-panel/components/form-render/components/form-item-list/components/IndefiniteNumberCheckBoxes/index.module.scss
  packages/editor/src/views/home/components/home-right/components/attribute-panel/components/form-render/components/form-item-list/components/IndefiniteNumberCheckBoxes/index.tsx
  packages/editor/src/views/home/components/home-right/components/attribute-panel/components/form-render/components/form-item-list/index.tsx
  packages/editor/src/views/home/components/home-right/components/attribute-panel/config.ts
  packages/editor/src/views/home/components/home-right/components/attribute-panel/index.vue
  packages/editor/types/auto-imports.d.ts
  packages/editor/types/components.d.ts
  packages/library/src/components/generic/form/button/index.vue
  packages/library/src/components/generic/form/checkboxes/index.vue
  packages/library/src/components/generic/input/textbox/index.vue
  packages/library/src/components/generic/show/circle/index.vue
  packages/library/src/components/generic/show/collapse/index.vue
  packages/library/src/components/generic/show/image/index.vue
  packages/library/src/components/generic/show/notice-bar/index.vue
  packages/library/src/components/generic/show/swipe/index.vue
  packages/library/src/hooks/use-library-component-custom-trigger.ts
  packages/types/src/panel.ts
Labels: enhancement

#100 fix: 事件触发器误报
  .eslintignore
  .eslintrc.cjs
  packages/editor/src/hooks/.gitkeep
  packages/library/src/components/business/show/swipe/.gitkeep
  packages/library/src/hooks/use-library-component-custom-trigger.ts
  packages/preview/types/auto-imports.d.ts
  packages/preview/types/components.d.ts
Labels: bug

#101 fix: 定义组件props时类型错误
  packages/library/src/utils/library.ts
Labels: bug

#102 Feat/layout merge
  packages/editor/src/hooks/use-recurse-query-schema.ts
  packages/editor/src/stores/code.ts
  packages/editor/src/utils/map-schemes-2-outline.ts
  packages/editor/src/views/home/components/edit-panel/components/slot-item.vue
  packages/editor/src/views/home/components/edit-panel/components/widget-render.vue
  packages/editor/src/views/home/components/edit-panel/index.vue
  packages/editor/src/views/home/components/edit-panel/use-parse-library.tsx
  packages/editor/src/views/home/components/home-left/components/outline-panel.vue
  packages/editor/src/views/home/components/home-right/components/attribute-panel/components/form-render/components/form-item-list/index.tsx
  packages/editor/types/components.d.ts
  packages/library/src/components/generic/container/layout/index.vue
  packages/library/src/components/generic/form/button/index.vue
  packages/library/src/components/generic/input/textbox/index.vue
  packages/library/src/components/generic/show/circle/index.vue
  packages/library/src/components/generic/show/collapse/index.vue
  packages/library/src/components/generic/show/image/index.vue
  packages/library/src/components/generic/show/notice-bar/index.vue
  packages/library/src/components/generic/show/swipe/index.vue
  packages/library/src/utils/library.ts
  packages/types/src/library-component.ts
Labels: enhancement

#108 docs: Update README.md
  README.md
Labels: documentation

#109 Docs/update pic
  docs/.vitepress/theme/components/home-preview.vue
  docs/public/img.png
  docs/public/img_1.png
  docs/public/img_2.png
  docs/public/img_3.png
  docs/public/img_4.png
  docs/public/img_5.png
  docs/public/img_6.png
  docs/public/img_7.png
  docs/public/img_8.png
  packages/editor/src/views/home/components/edit-panel/components/widget-render.vue
  packages/editor/src/views/home/components/edit-panel/index.vue
  packages/editor/src/views/home/components/edit-panel/use-drag-preview.tsx
  packages/editor/src/views/home/components/home-header/use-preset.ts
  packages/library/src/components/generic/container/layout/index.vue
Labels: bug, documentation
